In [1]:
def far_cel(F):
    # c=(F-32) x (5/9)
    celsius=(F-32) * (5/9)
    return celsius

In [2]:
far_cel(F=35)

1.6666666666666667

In [3]:
fahr=far_cel(F=276)

In [4]:
fahr

135.55555555555557

In [5]:
import pandas as pd

In [6]:
dem_health_data=pd.read_csv("Dem_Health_Full.txt",sep='\t')

In [7]:
dem_health_data.head()

,County,State,Population_Density,Poverty,Infant_Mortality,Suicide,Total_Births,Total_Deaths
0,Autauga,AL,82,10.4,5.9,16.6,3048.0,1867.0
1,Baldwin,AL,102,10.2,7.1,14.3,5471.0,4388.0
2,Barbour,AL,32,22.1,7.1,10.3,1835.0,1538.0
3,Bibb,AL,35,16.8,9.8,14.8,2801.0,2012.0
4,Blount,AL,86,11.9,9.0,14.4,3318.0,2453.0

In [8]:
dem_health_data.head(20)

,County,State,Population_Density,Poverty,Infant_Mortality,Suicide,Total_Births,Total_Deaths
0,Autauga,AL,82,10.4,5.9,16.6,3048.0,1867.0
1,Baldwin,AL,102,10.2,7.1,14.3,5471.0,4388.0
2,Barbour,AL,32,22.1,7.1,10.3,1835.0,1538.0
3,Bibb,AL,35,16.8,9.8,14.8,2801.0,2012.0
4,Blount,AL,86,11.9,9.0,14.4,3318.0,2453.0
5,Bullock,AL,18,26.2,13.3,-1111.1,1604.0,1381.0
6,Butler,AL,27,20.0,5.8,11.9,2874.0,2857.0
7,Calhoun,AL,184,16.4,9.5,13.6,4429.0,3915.0
8,Chambers,AL,59,16.2,7.5,12.8,2271.0,2424.0
9,Cherokee,AL,44,15.2,7.4,17.7,2659.0,2609.0
10,Chilton,AL,60,14.9,10.5,13.3,2671.0,2065.0
11,Choctaw,AL,16,18.7,10.8,9.4,2152.0,1742.0
12,Clarke,AL,22,19.2,7.1,8.9,1984.0,1444.0
13,Clay,AL,23,14.0,10.2,11.2,1748.0,1706.0
14,Cleburne,AL,26,14.0,7.0,30.1,1706.0,1540.0
15,Coffee,AL,67,13.7,2.9,13.1,2762.0,2210.0
16,Colbert,AL,92,14.0,8.2,15.1,3166.0,3087.0
17,Conecuh,AL,16,22.0,14.4,13.2,1872.0,1832.0
18,Coosa,AL,17,13.4,13.9,-1111.1,1273.0,1174.0
19,Covington,AL,36,17.5,6.2,10.7,2247.0,2499.0

In [9]:
def get_urban(df):
    urban=pd.loc[df['Population_Density']>=1000,:]
    return urban

In [10]:
urban_counties= get_urban(dem_health_data)

AttributeError: module 'pandas' has no attribute 'loc'

In [15]:
def get_urban(df):
    urban=df.loc[df['Poplation_Density']>=1000,:]
    return urban

In [14]:
urban_counties= get_urban(dem_health_data)

KeyError: 'Poplution_Density'

In [16]:
def get_urban(df):
    urban=df.loc[df['Population_Density']>=1000,:]
    return urban

In [17]:
urban_counties= get_urban(dem_health_data)

In [18]:
urban_counties

,County,State,Population_Density,Poverty,Infant_Mortality,Suicide,Total_Births,Total_Deaths
184,Alameda,CA,1964,10.7,4.8,7.6,65423.0,29143.0
190,Contra Costa,CA,1414,7.5,4.0,9.4,39653.0,20836.0
202,Los Angeles,CA,2447,17.7,5.4,7.9,457033.0,181018.0
213,Orange,CA,3785,10.6,4.7,7.6,135702.0,51060.0
217,Sacramento,CA,1412,13.7,5.6,10.9,58592.0,28774.0
221,San Francisco,CA,15837,12.0,3.9,11.0,25255.0,18969.0
224,San Mateo,CA,1558,6.8,4.1,7.1,30483.0,14256.0
226,Santa Clara,CA,1316,8.8,4.0,7.6,81257.0,26130.0
258,Denver,CO,3638,15.1,6.7,14.2,34354.0,13530.0
306,Fairfield,CT,1443,7.3,5.3,6.3,36336.0,21011.0
307,Hartford,CT,1193,9.2,6.3,7.6,31212.0,23682.0
310,New Haven,CT,1398,9.4,6.8,7.6,30738.0,23078.0
315,New Castle,DE,1227,8.2,9.4,11.1,21109.0,12346.0
317,Washington,DC,8966,17.5,10.9,6.0,22742.0,17375.0
323,Broward,FL,1475,12.5,6.5,13.3,67007.0,48248.0
332,Duval,FL,1068,12.8,10.3,14.5,36661.0,20511.0
345,Hillsborough,FL,1077,13.0,8.7,12.6,45253.0,26268.0
360,Miami-Dade,FL,1221,18.9,5.9,9.1,97091.0,55624.0
365,Orange,FL,1127,13.2,7.5,9.9,43304.0,19432.0
369,Pinellas,FL,3315,12.1,7.6,16.3,27592.0,37641.0
376,Seminole,FL,1303,9.1,5.5,13.0,13633.0,8050.0
415,Clayton,GA,1879,13.9,10.2,11.5,13391.0,4067.0
417,Cobb,GA,1952,9.6,6.4,9.2,31600.0,9967.0
428,DeKalb,GA,2528,13.2,9.2,9.7,32375.0,11887.0
444,Fulton,GA,1732,16.2,8.7,8.7,40860.0,18471.0
451,Gwinnett,GA,1678,8.2,6.5,9.6,34815.0,8012.0
545,Honolulu,HI,1509,10.5,7.3,9.5,38506.0,18565.0
608,Cook,IL,5608,14.5,8.5,7.5,247949.0,134307.0
614,DuPage,IL,2785,5.9,6.6,7.3,39133.0,17092.0
641,Lake,IL,1570,6.9,5.0,7.6,31544.0,11514.0
...,...,...,...,...,...,...,...,...
2917,Charlottesville City,VA,3941,17.8,7.4,11.6,2553.0,1737.0
2919,Colonial Heights City,VA,2349,7.4,6.7,13.8,2847.0,2044.0
2920,Covington City,VA,1094,12.7,6.6,-1111.1,834.0,1031.0
2921,Danville City,VA,1072,19.3,10.1,19.3,2861.0,3768.0
2923,Fairfax City,VA,3481,5.5,6.7,13.2,3271.0,2080.0
2924,Falls Church City,VA,5418,3.0,5.4,9.4,1866.0,790.0
2925,Franklin City,VA,1029,17.3,9.8,11.3,1154.0,1332.0
2926,Fredericksburg City,VA,1971,14.1,9.1,15.1,3936.0,2179.0
2928,Hampton City,VA,2811,13.1,11.6,8.5,5611.0,3410.0
2929,Harrisonburg City,VA,2303,17.9,5.9,10.4,2382.0,1298.0
2930,Hopewell City,VA,2216,16.4,10.5,14.4,3525.0,2654.0
2931,Lexington City,VA,2721,16.1,NaN,-1111.1,558.0,767.0
2932,Lynchburg City,VA,1356,17.5,9.2,11.0,4221.0,4057.0
2933,Manassas City,VA,3783,7.5,4.5,-1111.1,3593.0,959.0
2934,Manassas Park City,VA,4667,6.5,6.3,-1111.1,1915.0,347.0
2935,Martinsville City,VA,1362,17.9,2.4,19.9,1907.0,2598.0
2936,Newport News City,VA,2634,14.0,11.7,10.1,9587.0,4220.0
2937,Norfolk City,VA,4317,19.8,11.0,12.6,12143.0,6226.0
2939,Petersburg City,VA,1425,18.5,12.6,9.1,2706.0,2471.0
2941,Portsmouth City,VA,3021,16.5,14.2,13.4,4726.0,3254.0
2942,Radford City,VA,1484,18.5,6.8,19.1,1317.0,1023.0
2943,Richmond City,VA,3226,20.2,14.8,11.5,9287.0,6989.0
2944,Roanoke City,VA,2160,16.9,10.5,16.1,6456.0,6277.0
2945,Salem City,VA,1690,8.4,7.6,11.2,2528.0,3045.0
2946,Staunton City,VA,1184,13.1,6.6,14.5,2527.0,2964.0
2948,Virginia Beach City,VA,1766,8.0,7.1,9.8,18786.0,7655.0
2949,Waynesboro City,VA,1385,13.1,8.1,19.7,2731.0,2330.0
2950,Williamsburg City,VA,1376,17.5,11.2,16.4,1192.0,1288.0
2951,Winchester City,VA,2692,12.0,8.0,15.8,3336.0,2628.0
3086,Milwaukee,WI,3815,16.2,10.4,11.4,43885.0,26557.0

In [25]:
def get_urban(df, threshold):
    urban=df.loc[df['Population_Density']>=threshold,:]
    return urban

In [26]:
urban_counties= get_urban(dem_health_data, 10000)

In [21]:
urban_counties

,County,State,Population_Density,Poverty,Infant_Mortality,Suicide,Total_Births,Total_Deaths
221,San Francisco,CA,15837,12.0,3.9,11.0,25255.0,18969.0
1227,Suffolk,MA,11183,15.9,6.1,5.7,28649.0,16317.0
1780,Hudson,NJ,12926,15.0,7.4,4.8,26507.0,13726.0
1828,Bronx,NY,32300,26.8,6.8,5.8,68201.0,30886.0
1849,Kings,NY,35211,23.3,6.5,4.6,119171.0,54937.0
1856,New York,NY,69390,18.6,4.9,8.2,60627.0,34423.0
1866,Queens,NY,20520,15.4,5.2,4.7,92216.0,47876.0
2292,Philadelphia,PA,10832,20.1,10.4,10.7,64853.0,50895.0

In [30]:
def split_county_by_pop(df,threshold):
    urban=df.loc[df['Population Density'] >=threshold,:]
    rural=df.loc[df['Population Density'] <threshold,:]
    return [urban, rural]

In [32]:
urban_rural_counties=split_county_by_pop(dem_health_data, 1000)

KeyError: 'Population Density'

In [35]:
def split_county_by_pop(df,threshold):
    urban=df.loc[df['Population_Density'] >=threshold,:]
    rural=df.loc[df['Population_Density'] <threshold,:]
    return [urban, rural]

In [36]:
urban_rural_counties=split_county_by_pop(dem_health_data, 1000)

In [38]:
urban_rural_counties[1]

,County,State,Population_Density,Poverty,Infant_Mortality,Suicide,Total_Births,Total_Deaths
0,Autauga,AL,82,10.4,5.9,16.6,3048.0,1867.0
1,Baldwin,AL,102,10.2,7.1,14.3,5471.0,4388.0
2,Barbour,AL,32,22.1,7.1,10.3,1835.0,1538.0
3,Bibb,AL,35,16.8,9.8,14.8,2801.0,2012.0
4,Blount,AL,86,11.9,9.0,14.4,3318.0,2453.0
5,Bullock,AL,18,26.2,13.3,-1111.1,1604.0,1381.0
6,Butler,AL,27,20.0,5.8,11.9,2874.0,2857.0
7,Calhoun,AL,184,16.4,9.5,13.6,4429.0,3915.0
8,Chambers,AL,59,16.2,7.5,12.8,2271.0,2424.0
9,Cherokee,AL,44,15.2,7.4,17.7,2659.0,2609.0
10,Chilton,AL,60,14.9,10.5,13.3,2671.0,2065.0
11,Choctaw,AL,16,18.7,10.8,9.4,2152.0,1742.0
12,Clarke,AL,22,19.2,7.1,8.9,1984.0,1444.0
13,Clay,AL,23,14.0,10.2,11.2,1748.0,1706.0
14,Cleburne,AL,26,14.0,7.0,30.1,1706.0,1540.0
15,Coffee,AL,67,13.7,2.9,13.1,2762.0,2210.0
16,Colbert,AL,92,14.0,8.2,15.1,3166.0,3087.0
17,Conecuh,AL,16,22.0,14.4,13.2,1872.0,1832.0
18,Coosa,AL,17,13.4,13.9,-1111.1,1273.0,1174.0
19,Covington,AL,36,17.5,6.2,10.7,2247.0,2499.0
20,Crenshaw,AL,23,17.6,11.4,11.2,1745.0,1825.0
21,Cullman,AL,108,13.3,6.9,9.1,4897.0,4405.0
22,Dale,AL,87,15.8,7.9,10.8,3789.0,2259.0
23,Dallas,AL,45,25.0,9.6,8.4,3767.0,2752.0
24,DeKalb,AL,86,15.1,7.7,10.9,4665.0,3326.0
25,Elmore,AL,119,12.5,7.6,8.5,4707.0,2823.0
26,Escambia,AL,40,18.6,12.3,11.0,2519.0,2151.0
27,Etowah,AL,193,15.7,8.7,15.7,3810.0,4020.0
28,Fayette,AL,29,16.1,7.3,12.0,2145.0,2224.0
29,Franklin,AL,48,17.4,11.5,13.8,2169.0,1902.0
...,...,...,...,...,...,...,...,...
3111,Washburn,WI,21,9.7,7.0,11.4,1575.0,1846.0
3112,Washington,WI,293,4.6,3.8,9.8,4493.0,2572.0
3113,Waukesha,WI,682,4.1,3.0,8.0,13001.0,8256.0
3114,Waupaca,WI,70,7.4,8.4,10.5,2961.0,3352.0
3115,Waushara,WI,40,9.6,7.6,9.8,2324.0,2487.0
3116,Winnebago,WI,364,7.5,6.1,12.5,5441.0,3870.0
3117,Wood,WI,95,7.8,3.7,11.0,4352.0,3424.0
3118,Albany,WY,7,14.4,3.7,15.6,1881.0,925.0
3119,Big Horn,WY,4,13.2,6.2,21.9,1440.0,1304.0
3120,Campbell,WY,8,7.9,4.7,20.0,2548.0,841.0
3121,Carbon,WY,2,12.2,8.8,27.9,1775.0,1400.0
3122,Converse,WY,3,10.5,7.5,20.7,1486.0,894.0
3123,Crook,WY,2,8.5,0.0,20.8,634.0,481.0
3124,Fremont,WY,4,12.9,9.4,27.2,2440.0,1843.0
3125,Goshen,WY,6,14.6,7.7,15.2,1419.0,1276.0
3126,Hot Springs,WY,2,11.6,NaN,23.9,437.0,627.0
3127,Johnson,WY,2,9.6,0.0,14.0,674.0,739.0
3128,Laramie,WY,32,9.9,6.5,14.4,5807.0,3337.0
3129,Lincoln,WY,4,9.5,6.4,19.8,1907.0,983.0
3130,Natrona,WY,13,12.1,4.9,23.2,4508.0,2938.0
3131,Niobrara,WY,1,14.1,NaN,-1111.1,254.0,307.0
3132,Park,WY,4,11.7,3.9,17.4,1281.0,1173.0
3133,Platte,WY,4,11.5,5.0,22.2,901.0,983.0
3134,Sheridan,WY,11,11.5,4.8,20.5,1456.0,1455.0
3135,Sublette,WY,1,7.7,8.7,20.4,656.0,467.0
3136,Sweetwater,WY,4,8.6,10.2,27.9,2756.0,1264.0
3137,Teton,WY,5,5.6,3.5,13.1,1931.0,680.0
3138,Uinta,WY,10,10.6,7.0,18.4,3186.0,1060.0
3139,Washakie,WY,4,11.1,9.1,14.1,974.0,844.0
3140,Weston,WY,3,9.9,11.7,15.8,670.0,629.0

In [40]:
urban_rural_counties[0]

,County,State,Population_Density,Poverty,Infant_Mortality,Suicide,Total_Births,Total_Deaths
184,Alameda,CA,1964,10.7,4.8,7.6,65423.0,29143.0
190,Contra Costa,CA,1414,7.5,4.0,9.4,39653.0,20836.0
202,Los Angeles,CA,2447,17.7,5.4,7.9,457033.0,181018.0
213,Orange,CA,3785,10.6,4.7,7.6,135702.0,51060.0
217,Sacramento,CA,1412,13.7,5.6,10.9,58592.0,28774.0
221,San Francisco,CA,15837,12.0,3.9,11.0,25255.0,18969.0
224,San Mateo,CA,1558,6.8,4.1,7.1,30483.0,14256.0
226,Santa Clara,CA,1316,8.8,4.0,7.6,81257.0,26130.0
258,Denver,CO,3638,15.1,6.7,14.2,34354.0,13530.0
306,Fairfield,CT,1443,7.3,5.3,6.3,36336.0,21011.0
307,Hartford,CT,1193,9.2,6.3,7.6,31212.0,23682.0
310,New Haven,CT,1398,9.4,6.8,7.6,30738.0,23078.0
315,New Castle,DE,1227,8.2,9.4,11.1,21109.0,12346.0
317,Washington,DC,8966,17.5,10.9,6.0,22742.0,17375.0
323,Broward,FL,1475,12.5,6.5,13.3,67007.0,48248.0
332,Duval,FL,1068,12.8,10.3,14.5,36661.0,20511.0
345,Hillsborough,FL,1077,13.0,8.7,12.6,45253.0,26268.0
360,Miami-Dade,FL,1221,18.9,5.9,9.1,97091.0,55624.0
365,Orange,FL,1127,13.2,7.5,9.9,43304.0,19432.0
369,Pinellas,FL,3315,12.1,7.6,16.3,27592.0,37641.0
376,Seminole,FL,1303,9.1,5.5,13.0,13633.0,8050.0
415,Clayton,GA,1879,13.9,10.2,11.5,13391.0,4067.0
417,Cobb,GA,1952,9.6,6.4,9.2,31600.0,9967.0
428,DeKalb,GA,2528,13.2,9.2,9.7,32375.0,11887.0
444,Fulton,GA,1732,16.2,8.7,8.7,40860.0,18471.0
451,Gwinnett,GA,1678,8.2,6.5,9.6,34815.0,8012.0
545,Honolulu,HI,1509,10.5,7.3,9.5,38506.0,18565.0
608,Cook,IL,5608,14.5,8.5,7.5,247949.0,134307.0
614,DuPage,IL,2785,5.9,6.6,7.3,39133.0,17092.0
641,Lake,IL,1570,6.9,5.0,7.6,31544.0,11514.0
...,...,...,...,...,...,...,...,...
2917,Charlottesville City,VA,3941,17.8,7.4,11.6,2553.0,1737.0
2919,Colonial Heights City,VA,2349,7.4,6.7,13.8,2847.0,2044.0
2920,Covington City,VA,1094,12.7,6.6,-1111.1,834.0,1031.0
2921,Danville City,VA,1072,19.3,10.1,19.3,2861.0,3768.0
2923,Fairfax City,VA,3481,5.5,6.7,13.2,3271.0,2080.0
2924,Falls Church City,VA,5418,3.0,5.4,9.4,1866.0,790.0
2925,Franklin City,VA,1029,17.3,9.8,11.3,1154.0,1332.0
2926,Fredericksburg City,VA,1971,14.1,9.1,15.1,3936.0,2179.0
2928,Hampton City,VA,2811,13.1,11.6,8.5,5611.0,3410.0
2929,Harrisonburg City,VA,2303,17.9,5.9,10.4,2382.0,1298.0
2930,Hopewell City,VA,2216,16.4,10.5,14.4,3525.0,2654.0
2931,Lexington City,VA,2721,16.1,NaN,-1111.1,558.0,767.0
2932,Lynchburg City,VA,1356,17.5,9.2,11.0,4221.0,4057.0
2933,Manassas City,VA,3783,7.5,4.5,-1111.1,3593.0,959.0
2934,Manassas Park City,VA,4667,6.5,6.3,-1111.1,1915.0,347.0
2935,Martinsville City,VA,1362,17.9,2.4,19.9,1907.0,2598.0
2936,Newport News City,VA,2634,14.0,11.7,10.1,9587.0,4220.0
2937,Norfolk City,VA,4317,19.8,11.0,12.6,12143.0,6226.0
2939,Petersburg City,VA,1425,18.5,12.6,9.1,2706.0,2471.0
2941,Portsmouth City,VA,3021,16.5,14.2,13.4,4726.0,3254.0
2942,Radford City,VA,1484,18.5,6.8,19.1,1317.0,1023.0
2943,Richmond City,VA,3226,20.2,14.8,11.5,9287.0,6989.0
2944,Roanoke City,VA,2160,16.9,10.5,16.1,6456.0,6277.0
2945,Salem City,VA,1690,8.4,7.6,11.2,2528.0,3045.0
2946,Staunton City,VA,1184,13.1,6.6,14.5,2527.0,2964.0
2948,Virginia Beach City,VA,1766,8.0,7.1,9.8,18786.0,7655.0
2949,Waynesboro City,VA,1385,13.1,8.1,19.7,2731.0,2330.0
2950,Williamsburg City,VA,1376,17.5,11.2,16.4,1192.0,1288.0
2951,Winchester City,VA,2692,12.0,8.0,15.8,3336.0,2628.0
3086,Milwaukee,WI,3815,16.2,10.4,11.4,43885.0,26557.0

In [60]:
urban_rural_counties[0:1]

[                     County State  Population_Density  Poverty  \
 184                 Alameda    CA                1964     10.7
 190            Contra Costa    CA                1414      7.5
 202             Los Angeles    CA                2447     17.7
 213                  Orange    CA                3785     10.6
 217              Sacramento    CA                1412     13.7
 221           San Francisco    CA               15837     12.0
 224               San Mateo    CA                1558      6.8
 226             Santa Clara    CA                1316      8.8
 258                  Denver    CO                3638     15.1
 306               Fairfield    CT                1443      7.3
 307                Hartford    CT                1193      9.2
 310               New Haven    CT                1398      9.4
 315              New Castle    DE                1227      8.2
 317              Washington    DC                8966     17.5
 323                 Broward    FL                1475     12.5
 332                   Duval    FL                1068     12.8
 345            Hillsborough    FL                1077     13.0
 360              Miami-Dade    FL                1221     18.9
 365                  Orange    FL                1127     13.2
 369                Pinellas    FL                3315     12.1
 376                Seminole    FL                1303      9.1
 415                 Clayton    GA                1879     13.9
 417                    Cobb    GA                1952      9.6
 428                  DeKalb    GA                2528     13.2
 444                  Fulton    GA                1732     16.2
 451                Gwinnett    GA                1678      8.2
 545                Honolulu    HI                1509     10.5
 608                    Cook    IL                5608     14.5
 614                  DuPage    IL                2785      5.9
 641                    Lake    IL                1570      6.9
 ...                     ...   ...                 ...      ...
 2917   Charlottesville City    VA                3941     17.8
 2919  Colonial Heights City    VA                2349      7.4
 2920         Covington City    VA                1094     12.7
 2921          Danville City    VA                1072     19.3
 2923           Fairfax City    VA                3481      5.5
 2924      Falls Church City    VA                5418      3.0
 2925          Franklin City    VA                1029     17.3
 2926    Fredericksburg City    VA                1971     14.1
 2928           Hampton City    VA                2811     13.1
 2929      Harrisonburg City    VA                2303     17.9
 2930          Hopewell City    VA                2216     16.4
 2931         Lexington City    VA                2721     16.1
 2932         Lynchburg City    VA                1356     17.5
 2933          Manassas City    VA                3783      7.5
 2934     Manassas Park City    VA                4667      6.5
 2935      Martinsville City    VA                1362     17.9
 2936      Newport News City    VA                2634     14.0
 2937           Norfolk City    VA                4317     19.8
 2939        Petersburg City    VA                1425     18.5
 2941        Portsmouth City    VA                3021     16.5
 2942           Radford City    VA                1484     18.5
 2943          Richmond City    VA                3226     20.2
 2944           Roanoke City    VA                2160     16.9
 2945             Salem City    VA                1690      8.4
 2946          Staunton City    VA                1184     13.1
 2948    Virginia Beach City    VA                1766      8.0
 2949        Waynesboro City    VA                1385     13.1
 2950      Williamsburg City    VA                1376     17.5
 2951        Winchester City    VA                2692     12.0
 3086              Milwaukee    WI                3815     16.2

       Infant_Mortality  Suicide  Total_Births  Total_Deaths
 184                4.8      7.6       65423.0       29143.0
 190                4.0      9.4       39653.0       20836.0
 202                5.4      7.9      457033.0      181018.0
 213                4.7      7.6      135702.0       51060.0
 217                5.6     10.9       58592.0       28774.0
 221                3.9     11.0       25255.0       18969.0
 224                4.1      7.1       30483.0       14256.0
 226                4.0      7.6       81257.0       26130.0
 258                6.7     14.2       34354.0       13530.0
 306                5.3      6.3       36336.0       21011.0
 307                6.3      7.6       31212.0       23682.0
 310                6.8      7.6       30738.0       23078.0
 315                9.4     11.1       21109.0       12346.0
 317               10.9      6.0       22742.0       17375.0
 323                6.5     13.3       67007.0       48248.0
 332               10.3     14.5       36661.0       20511.0
 345                8.7     12.6       45253.0       26268.0
 360                5.9      9.1       97091.0       55624.0
 365                7.5      9.9       43304.0       19432.0
 369                7.6     16.3       27592.0       37641.0
 376                5.5     13.0       13633.0        8050.0
 415               10.2     11.5       13391.0        4067.0
 417                6.4      9.2       31600.0        9967.0
 428                9.2      9.7       32375.0       11887.0
 444                8.7      8.7       40860.0       18471.0
 451                6.5      9.6       34815.0        8012.0
 545                7.3      9.5       38506.0       18565.0
 608                8.5      7.5      247949.0      134307.0
 614                6.6      7.3       39133.0       17092.0
 641                5.0      7.6       31544.0       11514.0
 ...                ...      ...           ...           ...
 2917               7.4     11.6        2553.0        1737.0
 2919               6.7     13.8        2847.0        2044.0
 2920               6.6  -1111.1         834.0        1031.0
 2921              10.1     19.3        2861.0        3768.0
 2923               6.7     13.2        3271.0        2080.0
 2924               5.4      9.4        1866.0         790.0
 2925               9.8     11.3        1154.0        1332.0
 2926               9.1     15.1        3936.0        2179.0
 2928              11.6      8.5        5611.0        3410.0
 2929               5.9     10.4        2382.0        1298.0
 2930              10.5     14.4        3525.0        2654.0
 2931               NaN  -1111.1         558.0         767.0
 2932               9.2     11.0        4221.0        4057.0
 2933               4.5  -1111.1        3593.0         959.0
 2934               6.3  -1111.1        1915.0         347.0
 2935               2.4     19.9        1907.0        2598.0
 2936              11.7     10.1        9587.0        4220.0
 2937              11.0     12.6       12143.0        6226.0
 2939              12.6      9.1        2706.0        2471.0
 2941              14.2     13.4        4726.0        3254.0
 2942               6.8     19.1        1317.0        1023.0
 2943              14.8     11.5        9287.0        6989.0
 2944              10.5     16.1        6456.0        6277.0
 2945               7.6     11.2        2528.0        3045.0
 2946               6.6     14.5        2527.0        2964.0
 2948               7.1      9.8       18786.0        7655.0
 2949               8.1     19.7        2731.0        2330.0
 2950              11.2     16.4        1192.0        1288.0
 2951               8.0     15.8        3336.0        2628.0
 3086              10.4     11.4       43885.0       26557.0

 [137 rows x 8 columns]]

In [42]:
len(urban_rural_counties)

2

In [43]:
len(urban_rural_counties[0])

137

In [44]:
len(urban_rural_counties[1])

3004

In [62]:
urban_rural_counties[0,1]

TypeError: list indices must be integers or slices, not tuple

In [64]:
urban_rural_counties[0:0,1:1]

TypeError: list indices must be integers or slices, not tuple